title: Kaki's Dev Log
description: 버그는 줄이고 배움은 늘려가는 중

# 테마 및 경로 설정
remote_theme: jeffreytse/jekyll-theme-yat@v1.10.0
url: "https://fg-kaki.github.io"
baseurl: "/my-blog"

# yat 테마 전용 헤더 문구 설정
# (title이 메인 큰 글씨로 들어가고, tagline이 설명글로 나옵니다)
tagline: 배운 것을 정리하고 기록하는 공간

# yat 테마 전용 배너 이미지 설정
banner_img: /assets/images/banner.jpg

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate